# Generated by Django 4.2.7 on 2023-12-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPracticas1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(null=True, upload_to='attachments', verbose_name=''),
        ),
    ]
