# Generated by Django 4.2.7 on 2024-01-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPracticas1', '0002_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasepractica',
            name='guardados',
            field=models.IntegerField(null=True, verbose_name='Guardados'),
        ),
    ]
