# Generated by Django 4.2.7 on 2024-01-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPracticas1', '0003_fasepractica_guardados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasepractica',
            name='guardados',
            field=models.IntegerField(default=0, null=True, verbose_name='Guardados'),
        ),
    ]
