# Generated by Django 4.2.7 on 2024-01-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPracticas1', '0004_alter_fasepractica_guardados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionPracticas1.documento'),
        ),
    ]
