# Generated by Django 4.2.7 on 2024-03-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPracticas1', '0005_alter_archivo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='estado_practica',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Completado'), ('3', 'Vencido')], default='1', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='carrera',
            field=models.CharField(blank=True, choices=[('1', 'IC'), ('2', 'IICG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fasepractica',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Completado'), ('3', 'Vencido')], default='1', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fasepractica',
            name='fecha_conteo',
            field=models.DateField(max_length=50, verbose_name='Fecha conteo'),
        ),
    ]
