# Generated by Django 4.2.7 on 2024-03-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPracticas1', '0007_practica_conteo_practica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasepractica',
            name='estado',
            field=models.CharField(choices=[('1', 'Vencido'), ('2', 'Pendiente'), ('3', 'Completado')], default='1', verbose_name='Estado'),
        ),
    ]
