# Generated by Django 4.2.7 on 2024-03-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionPracticas1', '0009_practica_condicion_alter_fase_fase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practica',
            name='condicion',
            field=models.CharField(choices=[('1', 'Cursando'), ('2', 'Cancelado'), ('3', 'Aprobado'), ('4', 'Rechazado')], default='1', verbose_name='Estado'),
        ),
    ]
